language: java
jdk: oraclejdk7

install: mvn package -DbuildNumber=$TRAVIS_BUILD_NUMBER -DciSystem=travis -Dcommit=${TRAVIS_COMMIT:0:7}
after_success:
  - "git clone -b travis `git config --get remote.origin.url` target/travis"
  - "[[ \"$TRAVIS_BRANCH\" == \"master\" ]] && mvn deploy --settings target/travis/settings.xml"

notifications:
  email: false
  webhooks:
    - http://get.spout.org/hook
    - http://n.tkte.ch/h/518/lFp1AJUSCBcaAgv_Xui6rHYB

env:
  global:
    - secure: "anWNPmKwC4Cp3+QazgRpeRjG+e0WEVaHk1kihV4Ir0zO7X8OCxuvUasOmHpHFPDiPnWUoQJnJkTpB5tMNzdOpzjPWAdwcWk4+TILM13ZF+b5uyH7oHqphBYA+n77psnOq2c75hzpj8mpHOIvSR5ZOhS4WA3clTS/8+SN6oIV5QI="
    - secure: "ngRv9shgt/Fw5JmJ1m8npHL1RPTm8Ue2RBFLtezHGNxoeCuT5KT7cjcUYUoKzEtHQt3G4hpWcijBod6pNHxE6zxGg8SKg1CrL7OeZKE0Rj05dQU37x53LYWskUbXFC0OoJyGfevS92nfo3qARdn54QdVC4zI3rOy8NV5S5S4voY="
